name: Plagiarism Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-plagiarism:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
      contents: read

    steps:
    - name: Checkout the base repository
      uses: actions/checkout@v2

    - name: Checkout the plagiarism check tool
      uses: actions/checkout@v2
      with:
        repository: 'Gamezar/openai-plagiat-score'
        path: 'openai-plagiat-score'
        ref: 'main'

    - name: Install plagiarism check tool dependencies
      run: |
        cd openai-plagiat-score
        chmod +x install.sh
        ./install.sh

    - name: Get diff
      uses: technote-space/get-diff-action@v6

    - name: List all changed files
      id: files
      run: |
        echo "files=$GIT_DIFF" >> $GITHUB_ENV

    - name: Run plagiarism check on all changed files
      id: plagiarism_check
      run: |
        cd openai-plagiat-score
        output=""
        for file in ${{ env.files }}
        do
          result=$(python main.py "../$file")
          output+="$file: $result<br>"
        done
        echo "::set-output name=result::$output"

    - name: Post comment
      uses: KeisukeYamashita/create-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        comment: |
          **ChatGPT Check Results:**
          ${{ steps.plagiarism_check.outputs.result }}
    
    - name: Finalize check
      run: echo "Plagiarism check completed successfully."
